import { boolean, integer, pgEnum, pgTable, timestamp, uuid, varchar } from "drizzle-orm/pg-core";
import { encryptedText } from "../encryption";
import { teams } from "./teams";
import { servers } from "./servers";
import { environments } from "./projects";
import { resourceLimitColumns } from "./columns";

export const databaseEngineEnum = pgEnum("database_engine", ["postgresql", "mysql", "mariadb", "redis", "keydb", "dragonfly", "mongodb", "clickhouse"]);
export const databaseStatusEnum = pgEnum("database_status", ["idle", "provisioning", "running", "error"]);

export const databases = pgTable("databases", {
  id: uuid("id").defaultRandom().primaryKey(),
  teamId: uuid("team_id")
    .references(() => teams.id, { onDelete: "cascade" })
    .notNull(),
  environmentId: uuid("environment_id")
    .references(() => environments.id, { onDelete: "cascade" })
    .notNull(),
  serverId: uuid("server_id")
    .references(() => servers.id, { onDelete: "cascade" })
    .notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  engine: databaseEngineEnum("engine").default("postgresql").notNull(),
  image: varchar("image", { length: 255 }).default("postgres:16-alpine").notNull(),
  port: integer("port").default(5432).notNull(),
  // Redis has no login user — null for that engine, set for the others.
  username: varchar("username", { length: 255 }),
  // Encrypted at rest (AES-256-GCM, see ../encryption.ts).
  password: encryptedText("password").notNull(),
  // Redis has no named database either — null for that engine, set for the others.
  databaseName: varchar("database_name", { length: 255 }),
  // Publish the port on the server (off = reachable only by resources of the same environment, by name).
  // `port` is the published port and only matters while publicAccess is on.
  publicAccess: boolean("public_access").default(false).notNull(),
  // TLS with a self-signed certificate generated by the panel.
  ssl: boolean("ssl").default(false).notNull(),
  healthEnabled: boolean("health_enabled").default(true).notNull(),
  healthIntervalSeconds: integer("health_interval_seconds").default(30).notNull(),
  healthTimeoutSeconds: integer("health_timeout_seconds").default(10).notNull(),
  healthRetries: integer("health_retries").default(5).notNull(),
  ...resourceLimitColumns(),
  status: databaseStatusEnum("status").default("idle").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export type Database = typeof databases.$inferSelect;
export type NewDatabase = typeof databases.$inferInsert;
